name: main

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: print
        run: echo "windows"

  build-ubuntu: 
    runs-on: ubuntu-latest

    steps:
      - name: print
        run: echo "linux" 
